### ISSUE TITLE
Online courses Tina on GitLab

### ISSUE THREAD

**Issue by mkutmon** [BiGCAT-UM/BiGCaT-Teaching#1]
- MSP course INT3007 - Disease mechanisms (pathway + network analysis): https://mkutmon.gitlab.io/int3007/
- Postgrad course MolMed (Erasmus) - pathway + network analysis + automation: https://mkutmon.gitlab.io/molmed-wikipathways/
- Systems Biology Master course (MSB1014) - Network algorithms: https://mkutmon.gitlab.io/tutorial-network-algorithms/
- Systems Biology Master course (MSB1014) - Network inference: https://mkutmon.gitlab.io/tutorial-network-inference/

**Comment by mkutmon** [comment]
and a course on network data from Susan: https://coort.gitlab.io/tutorial-network-data/

**Comment by LaurenDupuis** [comment]
Updated, thank you
